-- 코드를 입력하세요
SELECT
    WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    -- CASE
    --     WHEN FREEZER_YN IS NULL THEN 'N'
    --     WHEN FREEZER_YN IS NOT NULL THEN 'Y'
    -- END AS FREEZER_YN
    NVL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
    WHERE WAREHOUSE_NAME LIKE '%경기%'
        ORDER BY WAREHOUSE_ID ASC;